('vaibhav.swaminathan@eonerc.rwth-aachen.de', 'bitte_Ã¤ndern!')
{'detail': 'The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.', 'status': 500, 'title': 'Internal Server Error', 'type': 'about:blank'}
{'detail': 'The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.', 'status': 500, 'title': 'Internal Server Error', 'type': 'about:blank'}
{'detail': 'The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.', 'status': 500, 'title': 'Internal Server Error', 'type': 'about:blank'}
['detail', 'status', 'title', 'type']
{'detail': 'The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.', 'status': 500, 'title': 'Internal Server Error', 'type': 'about:blank'}
Traceback (most recent call last):
  File "/home/vaibhavs/Master_Thesis/ma-vaibhav/Code/get_timeseries.py", line 91, in <module>
    vals = dat.get_gps_timeseries(data=['ADS.fAHUFlapETAActADS'])
  File "/home/vaibhavs/Master_Thesis/ma-vaibhav/Code/get_timeseries.py", line 75, in get_gps_timeseries
    df = pd.DataFrame(rj['data']).rename({'time': 'time', 'value': i}, axis=1).set_index(
KeyError: 'data'
